# Generated by Django 5.2.5 on 2025-10-07 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_available_from_doctor_available_to_and_more'),
        ('patient', '0008_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='patient_full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
    ]
