# Generated by Django 5.2.5 on 2025-10-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_booking_patient_full_name_alter_booking_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='patient_full_name',
        ),
    ]
