# Generated by Django 5.2.5 on 2025-10-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_remove_booking_patient_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='patient_full_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
